<?php
/**
 * apiBase 相当于 API模块下的公共控制器 不需要登录场景的类请继承这个控制器
 * Created by Edmund.
 * Motto: 现在的努力是为了小时候吹过的牛逼！
 * Date: 2020/4/5
 * Time: 18:56
 */
namespace app\api\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController {
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function show(...$args) {
        throw new HttpResponseException(show(...$args));
    }
}