<?php
/**
 * AuthBase 需要登录才能访问的接口请继承这个类
 * Created by Edmund.
 * Motto: 加油，凤凰苑 (๑❛ᴗ❛๑)
 * Date: 2020/4/5
 * Time: 19:04
 */

namespace app\api\controller;

class AuthBase extends ApiBase {
    public $userId = 0;
    public $username = "";
    public $accessToken = "";
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header("access-token");
        if(!$this->accessToken || !$this->isLogin()) {
            return $this->show(config("status.not_login"),"没有登录");
        }
        return true;
    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isLogin() {
        $name = config("redis.token_pre"). $this->accessToken;
        $userInfo = cache($name);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->username = $userInfo['username'];
            $this->userId = $userInfo['id'];
            return true;
        }
        return false;
    }
}